<?php
$custom_background_id = get_theme_mod( 'custom_background' );
$image	= wp_get_attachment_image_src( $custom_background_id , 'full' );

if ($image == null) {
  $image = 'url(nobackgroundset.png)';
}

return "
/* do not edit this file! it is generated by wordpress! */
\$pageBackground: 	". $image .";
";
?>
